# 公共环境
# application.yaml
spring:
  # 配置文件
  profiles:
    # 激活环境
    active: dev
  # SpringBoot 2.6.0开始使用基于PathPatternParser的路径匹配，而Springfox版本一直没有更新还是使用的AntPathMatcher
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER